import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar1 from "./nopage/components/navbar1"
import Navbar2 from "./nopage/components/navbar2"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ci`}
      >
        <Navbar1/>
        <Navbar2/>
        {children}
      </body>
    </html>
  );
}
